#
# Labtainer Dockerfile
#

ARG registry
FROM $registry/labtainer.base2
#FROM $registry/labtainer.network
#FROM $registry/labtainer.centos
#FROM $registry/labtainer.lamp

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version

LABEL version=$version

ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

#
# Install packages for video LSB watermark lab
#
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-opencv \
    python3-numpy \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#
# Install the system files found in the _system directory
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /

RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo

#
# Perform all root operations before USER command
#
USER $user_name
ENV HOME /home/$user_name

#
# Install files in the user home directory
#
ADD $labdir/$imagedir/home_tar/home.tar $HOME

# remove after docker fixes problem with empty tars
RUN rm -f $HOME/home.tar

ADD $labdir/$lab.tar.gz $HOME

#
# The first thing that executes on the container.
#
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
